package org.community.core.model.pojo;

import java.util.Date;

public class OauthRefreshToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.token_id
     *
     * @mbggenerated
     */
    private String tokenId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.create_time
     *
     * @return the value of oauth_refresh_token.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.create_time
     *
     * @param createTime the value for oauth_refresh_token.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.token_id
     *
     * @return the value of oauth_refresh_token.token_id
     *
     * @mbggenerated
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.token_id
     *
     * @param tokenId the value for oauth_refresh_token.token_id
     *
     * @mbggenerated
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId == null ? null : tokenId.trim();
    }
}