package org.community.core.model.pojo;

public class UserPrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_privilege.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_privilege.privilege
     *
     * @mbggenerated
     */
    private String privilege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_privilege.user_id
     *
     * @return the value of user_privilege.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_privilege.user_id
     *
     * @param userId the value for user_privilege.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_privilege.privilege
     *
     * @return the value of user_privilege.privilege
     *
     * @mbggenerated
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_privilege.privilege
     *
     * @param privilege the value for user_privilege.privilege
     *
     * @mbggenerated
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege == null ? null : privilege.trim();
    }
}