package org.community.core.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.community.core.model.pojo.OauthCode;
import org.community.core.model.pojo.OauthCodeExample;

public interface OauthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated
     */
    int countByExample(OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated
     */
    int deleteByExample(OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated
     */
    int insert(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated
     */
    int insertSelective(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated
     */
    List<OauthCode> selectByExampleWithBLOBs(OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated
     */
    List<OauthCode> selectByExample(OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OauthCode record, @Param("example") OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OauthCode record, @Param("example") OauthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OauthCode record, @Param("example") OauthCodeExample example);
}