package org.community.core.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.community.core.model.pojo.OauthRefreshToken;
import org.community.core.model.pojo.OauthRefreshTokenExample;
import org.community.core.model.pojo.OauthRefreshTokenWithBLOBs;

public interface OauthRefreshTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    int countByExample(OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    int deleteByExample(OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    int insert(OauthRefreshTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    int insertSelective(OauthRefreshTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    List<OauthRefreshTokenWithBLOBs> selectByExampleWithBLOBs(OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    List<OauthRefreshToken> selectByExample(OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OauthRefreshTokenWithBLOBs record, @Param("example") OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OauthRefreshTokenWithBLOBs record, @Param("example") OauthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OauthRefreshToken record, @Param("example") OauthRefreshTokenExample example);
}