package org.community.core.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.community.core.model.pojo.UserPrivilege;
import org.community.core.model.pojo.UserPrivilegeExample;

public interface UserPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbggenerated
     */
    int countByExample(UserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbggenerated
     */
    int deleteByExample(UserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbggenerated
     */
    int insert(UserPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbggenerated
     */
    int insertSelective(UserPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbggenerated
     */
    List<UserPrivilege> selectByExample(UserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPrivilege record, @Param("example") UserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPrivilege record, @Param("example") UserPrivilegeExample example);
}